version: '3.3'
services:
    app:
        build: .
        depends_on: 
            - db
        ports:
            - "3306:3306"

    db:
        image: mysql/mysql-server:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
